#include "openaicompatibleprovider.h"
#include <KLocalizedString>
#include <QNetworkRequest>
#include <QDebug>

OpenAICompatibleProvider::OpenAICompatibleProvider(QObject *parent)
    : ProviderBackend(parent)
{
}

QString OpenAICompatibleProvider::model() const { return m_model; }
void OpenAICompatibleProvider::setModel(const QString &model)
{
    if (m_model != model) {
        m_model = model;
        setPricingModel(m_model);
        Q_EMIT modelChanged();
    }
}

void OpenAICompatibleProvider::refreshImpl()
{
    if (!hasApiKey()) {
        setErrorDetails(i18n("No API key configured"), ProviderErrorKind::Configuration);
        setConnected(false);
        return;
    }

    beginRefresh();
    setLoading(true);
    clearError();
    m_pendingRequests = 0;
    fetchModels();
}

void OpenAICompatibleProvider::fetchModels()
{
    const QUrl url(QStringLiteral("%1/models").arg(effectiveBaseUrl(defaultBaseUrl())));
    addPendingRequest();
    const int gen = currentGeneration();
    QNetworkReply *reply = networkManager()->get(createRequest(url));
    trackReply(reply);
    connect(reply, &QNetworkReply::finished, this, [this, reply, gen]() {
        if (!isCurrentGeneration(gen)) { reply->deleteLater(); return; }
        onModelsFinished(reply);
    });
}

void OpenAICompatibleProvider::testConnectionNow()
{
    if (!hasApiKey()) {
        setErrorDetails(i18n("No API key configured"), ProviderErrorKind::Configuration);
        return;
    }
    beginRefresh();
    setLoading(true);
    clearError();
    m_pendingRequests = 0;
    fetchManualProbe();
}

void OpenAICompatibleProvider::fetchManualProbe()
{
    // Explicit user action only. This request may consume quota or money.
    QUrl url(QStringLiteral("%1/chat/completions").arg(effectiveBaseUrl(defaultBaseUrl())));

    QNetworkRequest request = createRequest(url);

    QJsonObject payload;
    payload.insert(QStringLiteral("model"), m_model);
    payload.insert(QStringLiteral("max_tokens"), 1);

    QJsonArray messages;
    QJsonObject msg;
    msg.insert(QStringLiteral("role"), QStringLiteral("user"));
    msg.insert(QStringLiteral("content"), QStringLiteral("hi"));
    messages.append(msg);
    payload.insert(QStringLiteral("messages"), messages);

    QByteArray body = QJsonDocument(payload).toJson(QJsonDocument::Compact);
    m_lastRequestBody = body;

    addPendingRequest();
    int gen = currentGeneration();
    QNetworkReply *reply = networkManager()->post(request, body);
    trackReply(reply);
    connect(reply, &QNetworkReply::finished, this, [this, reply, gen]() {
        if (!isCurrentGeneration(gen)) { reply->deleteLater(); return; }
        onCompletionFinished(reply);
    });
}

void OpenAICompatibleProvider::onModelsFinished(QNetworkReply *reply)
{
    decrementPendingRequest();
    const int httpStatus = reply->attribute(QNetworkRequest::HttpStatusCodeAttribute).toInt();
    if (reply->error() != QNetworkReply::NoError) {
        if (httpStatus == 401) {
            setErrorDetails(i18n("Invalid API key"), ProviderErrorKind::Authentication, httpStatus);
        } else if (httpStatus == 403) {
            setErrorDetails(i18n("Model listing is not permitted for this key"), ProviderErrorKind::Permission, httpStatus);
        } else if (httpStatus == 404) {
            setErrorDetails(i18n("This provider has no safe read-only monitoring endpoint"), ProviderErrorKind::Unsupported, httpStatus);
        } else {
            setNetworkError(reply, i18n("Models API unavailable: %1", reply->errorString()));
        }
        setConnected(false);
    } else {
        reply->readAll();
        setConnected(true);
        setUsageSource(QStringLiteral("connectivity_read_only"));
        setCostSource(QStringLiteral("unknown"));
        setDataQuality(QStringLiteral("connectivity_only"));
    }
    reply->deleteLater();
    onAllRequestsDone();
}

void OpenAICompatibleProvider::parseRateLimitHeaders(QNetworkReply *reply)
{
    // Delegate to centralized base class parser
    ProviderBackend::parseRateLimitHeaders(reply, "x-ratelimit-");
}

void OpenAICompatibleProvider::parseUsageBody(QNetworkReply *reply)
{
    QByteArray data = reply->readAll();
    QJsonDocument doc = QJsonDocument::fromJson(data);
    if (!doc.isNull()) {
        QJsonObject root = doc.object();
        QJsonObject usage = root.value(QStringLiteral("usage")).toObject();
        if (!usage.isEmpty()) {
            qint64 promptTokens = usage.value(QStringLiteral("prompt_tokens")).toInteger(0);
            qint64 completionTokens = usage.value(QStringLiteral("completion_tokens")).toInteger(0);
            // This request is a connectivity/rate-limit probe generated by
            // the widget. Keep it separate from user usage and spend.
            m_sessionProbeInputTokens += promptTokens;
            m_sessionProbeOutputTokens += completionTokens;
            m_sessionProbeRequestCount++;
            setProbeUsage(m_sessionProbeInputTokens,
                          m_sessionProbeOutputTokens,
                          m_sessionProbeRequestCount);
            setUsageSource(QStringLiteral("connectivity_probe"));
            setCostSource(QStringLiteral("connectivity_probe"));
            setDataQuality(QStringLiteral("probe_only"));
        }
    }
}

void OpenAICompatibleProvider::onCompletionFinished(QNetworkReply *reply)
{
    decrementPendingRequest();

    if (reply->error() != QNetworkReply::NoError) {
        int httpStatus = reply->attribute(QNetworkRequest::HttpStatusCodeAttribute).toInt();

        // Retry transient errors (retryRequest takes ownership of reply)
        if (isRetryableStatus(httpStatus)) {
            addPendingRequest(); // re-increment since retry is pending
            retryRequest(reply, reply->url(), m_lastRequestBody,
                         [this](QNetworkReply *r) { onCompletionFinished(r); });
            return;
        }

        if (httpStatus == 401) {
            setErrorDetails(i18n("Invalid API key"), ProviderErrorKind::Authentication, httpStatus);
        } else if (httpStatus == 429) {
            setErrorDetails(i18n("Rate limited"), ProviderErrorKind::RateLimit, httpStatus,
                            retryAfterForReply(reply));
            // Still parse headers on 429
            parseRateLimitHeaders(reply);
        } else {
            setNetworkError(reply, i18n("API error: %1 (HTTP %2)",
                                        reply->errorString(),
                                        QString::number(httpStatus)));
        }

        reply->deleteLater();

        if (httpStatus != 429 && httpStatus != 401) {
            onAllRequestsDone();
            return;
        }
    } else {
        parseRateLimitHeaders(reply);
        parseUsageBody(reply);
        reply->deleteLater();
        setConnected(true);
    }

    onAllRequestsDone();
}

void OpenAICompatibleProvider::onAllRequestsDone()
{
    if (m_pendingRequests <= 0) {
        setLoading(false);
        updateLastRefreshed();
        Q_EMIT dataUpdated();

    }
}

void OpenAICompatibleProvider::addPendingRequest()
{
    m_pendingRequests++;
}

bool OpenAICompatibleProvider::decrementPendingRequest()
{
    m_pendingRequests--;
    return m_pendingRequests <= 0;
}
