#!/usr/bin/env python3
"""Generate the GitHub wiki mirror from the canonical user guide."""

from __future__ import annotations

import argparse
import difflib
import re
import sys
from pathlib import Path


ROOT = Path(__file__).resolve().parents[1]
SOURCE_DIR = ROOT / "docs" / "user-guide"
WIKI_DIR = ROOT / "docs" / "wiki"
LEGACY_WIKI_DIR = ROOT / "wiki"
REPOSITORY_BLOB_URL = "https://github.com/loofiboss-bit/plasma-ai-usage-monitor/blob/main/"

PAGE_MAP = {
    "README.md": "Home.md",
    "installation.md": "Installation.md",
    "getting-started.md": "Getting-Started.md",
    "understanding-data.md": "Understanding-the-Data.md",
    "providers.md": "Providers.md",
    "subscriptions.md": "Subscription-Tools.md",
    "runway-guardrails.md": "Runway-Guardrails.md",
    "history-and-integrations.md": "History-and-Integrations.md",
    "troubleshooting.md": "Troubleshooting.md",
    "privacy-and-security.md": "Privacy-and-Security.md",
}

SIDEBAR = """<!-- Generated by scripts/generate_wiki_docs.py; do not edit. -->
## AI Usage Monitor

- [Home](Home)
- [Installation](Installation)
- [Getting started](Getting-Started)
- [Understanding the data](Understanding-the-Data)
- [Providers](Providers)
- [Subscription tools](Subscription-Tools)
- [Runway guardrails](Runway-Guardrails)
- [History and integrations](History-and-Integrations)
- [Troubleshooting](Troubleshooting)
- [Privacy and security](Privacy-and-Security)

---

- [Latest release](https://github.com/loofiboss-bit/plasma-ai-usage-monitor/releases/latest)
- [Report a bug](https://github.com/loofiboss-bit/plasma-ai-usage-monitor/issues)
"""

MARKDOWN_LINK = re.compile(r"(?P<prefix>!?\[[^]]*\]\()(?P<target>[^)]+)(?P<suffix>\))")


def rewrite_link(target: str) -> str:
    if target.startswith(("https://", "http://", "mailto:", "#")):
        return target

    path, separator, fragment = target.partition("#")
    if path in PAGE_MAP:
        rewritten = PAGE_MAP[path].removesuffix(".md")
    elif path.startswith("../"):
        rewritten = REPOSITORY_BLOB_URL + "docs/" + path.removeprefix("../")
    else:
        rewritten = path
    return rewritten + (separator + fragment if separator else "")


def render_page(source_name: str) -> str:
    source = (SOURCE_DIR / source_name).read_text(encoding="utf-8")
    body = MARKDOWN_LINK.sub(
        lambda match: match.group("prefix")
        + rewrite_link(match.group("target"))
        + match.group("suffix"),
        source,
    )
    marker = (
        f"<!-- Generated from docs/user-guide/{source_name} by "
        "scripts/generate_wiki_docs.py; do not edit. -->\n"
    )
    return marker + body


def expected_files() -> dict[str, str]:
    result = {target: render_page(source) for source, target in PAGE_MAP.items()}
    result["_Sidebar.md"] = SIDEBAR
    return result


def check() -> int:
    failures: list[str] = []
    expected = expected_files()
    actual_names = {path.name for path in WIKI_DIR.glob("*.md")}
    expected_names = set(expected)

    for name in sorted(expected_names - actual_names):
        failures.append(f"missing generated wiki page: docs/wiki/{name}")
    for name in sorted(actual_names - expected_names):
        failures.append(f"unexpected wiki page: docs/wiki/{name}")
    if LEGACY_WIKI_DIR.exists() and any(LEGACY_WIKI_DIR.iterdir()):
        failures.append("legacy root wiki/ directory must not exist")

    for name, wanted in expected.items():
        destination = WIKI_DIR / name
        if not destination.is_file():
            continue
        current = destination.read_text(encoding="utf-8")
        if current == wanted:
            continue
        diff = "".join(
            difflib.unified_diff(
                current.splitlines(keepends=True),
                wanted.splitlines(keepends=True),
                fromfile=f"docs/wiki/{name}",
                tofile=f"generated/{name}",
                n=2,
            )
        )
        failures.append(f"generated wiki page is stale: docs/wiki/{name}\n{diff}")

    if failures:
        print("\n".join(failures), file=sys.stderr)
        print("Run: python3 scripts/generate_wiki_docs.py", file=sys.stderr)
        return 1
    print("Wiki documentation is generated from docs/user-guide and up to date.")
    return 0


def write() -> int:
    WIKI_DIR.mkdir(parents=True, exist_ok=True)
    for name, content in expected_files().items():
        (WIKI_DIR / name).write_text(content, encoding="utf-8")
    print(f"Generated {len(PAGE_MAP) + 1} wiki files in docs/wiki.")
    return 0


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--check", action="store_true", help="fail when generated files drift")
    args = parser.parse_args()
    return check() if args.check else write()


if __name__ == "__main__":
    raise SystemExit(main())
