#!/usr/bin/env python3
"""Generate the release-facing provider capability and traffic matrix."""
from __future__ import annotations

import argparse
import json
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
CATALOG = ROOT / "package/contents/catalog/providers-v4.json"
OUTPUT = ROOT / "docs/provider-capabilities.md"

LEVEL_LABELS = {
    "actual_usage_spend": "Actual account usage and spend",
    "actual_key_usage": "Actual key usage and balance",
    "balance_connectivity": "Balance and connectivity",
    "gateway_aggregate": "Gateway aggregate usage and spend",
    "connectivity_only": "Connectivity/model discovery only",
}


def scheduled_call(provider: dict) -> str:
    safe = provider["safeRefresh"]
    paths = safe.get("paths") or [safe.get("path")]
    rendered = [f"`{safe['method']} {path}`" for path in paths if path]
    return "; ".join(rendered) if rendered else "None"


def render(catalog: dict) -> str:
    lines = [
        "# Provider capabilities — Catalog v7",
        "",
        "<!-- Generated by scripts/generate_provider_capabilities.py; do not edit manually. -->",
        "",
        "This matrix is generated from the same Catalog v7 descriptors used by the widget. "
        "Connectivity never implies account-wide usage or spend. All scheduled calls are read-only; "
        "manual inference tests are separate and may consume quota or money.",
        "",
        "| Provider | Monitoring level | Scheduled call(s) | Scope | Request budget | Billable background request |",
        "| --- | --- | --- | --- | ---: | --- |",
    ]
    for provider in catalog["providers"]:
        auth = provider["auth"]
        scope = "public" if auth["scheme"] == "none" else (
            "gateway" if provider["monitoringLevel"] == "gateway_aggregate" else "credential/account"
        )
        lines.append(
            f"| {provider['displayName']} | {LEVEL_LABELS[provider['monitoringLevel']]} | "
            f"{scheduled_call(provider)} | {scope} | {provider['safeRefresh']['requestBudget']} | No |"
        )

    lines.extend([
        "",
        "## Capability semantics",
        "",
        "- `usage` and `cost` mean provider- or gateway-reported values, not traffic manufactured by the widget.",
        "- `creditBalance` is never summed across currencies.",
        "- `rateLimits` means a live limit/remaining pair; published caps use published-documentation metadata.",
        "- Missing values remain unavailable in QML, SQLite, exports, alerts, and Prometheus.",
        "- Fireworks billing remains deferred until a real read-only billing fixture is validated.",
        "",
        "## Runway and scope support",
        "",
        "- OpenAI usage and cost totals use bounded, cursor-complete pagination. A partial traversal is never published as a complete total.",
        "- OpenAI usage can group by reported model and project. OpenAI cost can group by project and line item; model-level cost is not inferred.",
        "- Anthropic usage retains reported model, workspace, and service-tier detail; cost retains provider-reported line items.",
        "- Aggregate rows drive daily status and runway. Scoped rows are detail-only and never added to aggregate totals a second time.",
        "- Only synchronized remaining-plus-limit quota windows and compatible completed UTC daily spend can produce runway forecasts.",
        "- Raw scope identifiers remain local and are absent from default webhook and Prometheus payloads.",
        "",
        "## Setup guides",
        "",
        "- [Gemini Developer API](provider-setup/gemini.md)",
        "- [LiteLLM Proxy](provider-setup/litellm.md)",
        "- [Cerebras](provider-setup/cerebras.md)",
        "- [Fireworks AI](provider-setup/fireworks.md)",
        "- [Perplexity API](provider-setup/perplexity.md)",
        "",
    ])
    return "\n".join(lines)


def main() -> None:
    parser = argparse.ArgumentParser()
    parser.add_argument("--check", action="store_true")
    parser.add_argument("--stdout", action="store_true")
    args = parser.parse_args()
    catalog = json.loads(CATALOG.read_text(encoding="utf-8"))
    content = render(catalog)
    if args.stdout:
        print(content, end="")
    elif args.check:
        if not OUTPUT.exists() or OUTPUT.read_text(encoding="utf-8") != content:
            raise SystemExit("Provider capability docs are stale; run scripts/generate_provider_capabilities.py")
        print(f"Provider capability docs OK: {len(catalog['providers'])} catalog profiles")
    else:
        OUTPUT.write_text(content, encoding="utf-8")
        print(f"Wrote {OUTPUT.relative_to(ROOT)}")


if __name__ == "__main__":
    main()
